config/routes.rb
RailsClassWebsite::Application.routes.draw do
  devise_for :users
  resources :users

  resources :blogposts do
    resources :comments
  end
  get "pages/home"
  get "pages/schedule"

  root 'blogposts#index'

end

app/models/blogpost.rb
class Blogpost < ActiveRecord::Base
    belongs_to :user
    has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :blogpost
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :blogposts
  has_many :comments

  def admin?
    return admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController

  before_filter :authenticate_user!,
    only: [:new, :create, :edit, :update, :destroy]

  def new
    @blogpost = Blogpost.new
  end

  def create
    if current_user.blogposts.create blogpost_params
      flash[:success] = "Created New Blogpost"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @blogpost = Blogpost.find(params[:id])
  end

  def update
    @blogpost = Blogpost.find(params[:id])
    if @blogpost.update_attributes(blogpost_params)
      flash[:success] = "Edited Blogpost"
      redirect_to @blogpost
    else
      render 'edit'
    end
  end

  def show
    @blogpost = Blogpost.find(params[:id])
    @comments = Comment.all
    @new_comment = Comment.new
  end

  def index
    @blogposts = Blogpost.all
  end

  private
    def blogpost_params
      params.require(:blogpost).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    blogpost = params[:blogpost_id]

    comment = Comment.new(comments_params)
    comment.blogpost_id = blogpost.id

    if current_user.comments.add(comment)
      flash[:success] = "Posted Comment"
      redirect_to blogpost
    else
      render blogpost
    end
  end

  def update

  end

  private
    def comments_params
      params.require(:comment).permit(:comment)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def schedule
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogposts/edit.html.haml
%h1 Edit Blogpost
= form_for @blogpost do |f|
  .form-group
    = f.label :title
    = f.text_field :title
  .form-group
    = f.label :body
    = f.text_area :body
  = f.submit "Submit Edits", class: 'btn btn-large btn-primary'

app/views/blogposts/index.html.haml
%h1 Rails Class

- if user_signed_in? and current_user.admin?
  .new-blogpost-button= link_to "New Blogpost", new_blogpost_path, class: "btn btn-primary"
.blog-list
  %ul
    - for blogpost in @blogposts
      %li.blogpost
        %span.title-row
          .title= link_to blogpost.title, blogpost
          .author
            By
            = link_to blogpost.user.email, blogpost.user
          .edit= link_to "Edit", edit_blogpost_path(blogpost), class: "btn btn-primary"

        .body= blogpost.body

app/views/blogposts/new.html.haml
%h1 New Blogpost

= form_for @blogpost do |f|
  .form-group
    = f.label :title
    = f.text_field :title
  .form-group
    = f.label :body
    = f.text_area :body
  = f.submit "Create New Blogpost", class: 'btn btn-large btn-primary'

app/views/blogposts/show.html.haml
.blogpost
  %span.title-row
    .title= @blogpost.title
    .author
      By
      = link_to @blogpost.user.email, @blogpost.user

  .body= @blogpost.body

  .footer
    .date
      Created
      = time_ago_in_words @blogpost.created_at
      ago.

.comments-area
  .title Comments
  .new-comment
    = form_for ([@blogpost, @new_comment]) do |f|
      = f.text_area :comment
      = f.submit "Submit", class: 'btn btn-primary btn-medium'

  %ul.comments
    - @comments.each do |comment|
      %li.comment
        .author= comment.user.email
        .comment= comment.comment

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      #logo= link_to "ruby class", root_path
      %nav
        %ul.nav.pull-right
          %li= link_to "Home", root_path
          %li= link_to "Assignments", "#"
          %li= link_to "Schedule", 'pages/schedule'
          - if user_signed_in?
            %li= link_to "Log Out", destroy_user_session_path, method: :delete
          - else
            %li= link_to "Sign up", new_user_registration_path
            %li= link_to "Log In", new_user_session_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header'%>
    <div class="container">
        <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>

        <%= yield %>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>

app/views/pages/home.html.haml
- provide :title, "Home"

app/views/pages/schedule.html.haml
%h1 Pages#schedule
%p Find me in app/views/pages/schedule.html.haml